# Sample configuration file for Arak indexing service

ethrpc = "https://mainnet.infura.io/v3/<INFURA_PROJECT_ID>"

[[event]]
name = "uniswapv2_pair_created"
contract = "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
signature = "event PairCreated(address indexed token0, address indexed token1, address pair, uint);"

[[event]]
name = "uniswapv2_sync"
contract = "*"
signature = "event Sync(uint112 reserve0, uint112 reserve1);"
