# Sample configuration file for Arak indexing service

ethrpc = "https://mainnet.infura.io/v3/<INFURA_PROJECT_ID>"
database = "file://<DB_PATH>"

[[event]]
name = "cowprotocol_settlements"
start = 12593265
contract = "0x9008d19f58aabd9ed0d60971565aa8510560ab41"
signature = "event Settlement(address indexed solver)"

[[event]]
name = "cowprotocol_inbound_transfers"
start = 12593265
contract = "*"
topics = ["0x0000000000000000000000009008d19f58aabd9ed0d60971565aa8510560ab41"]
signature = "event Transfer(address indexed from, address indexed to, uint256 value)"
